CREATE TABLE MY_BOOKINGS(
   _id INTEGER PRIMARY KEY AUTOINCREMENT,
   CRN INT NOT NULL UNIQUE,
   CAB_COMPANY INT NOT NULL,
   CAB_TYPE TEXT NOT NULL,
   CAR_NUMBER TEXT,
   CAR_MODEL TEXT,
   DRIVER_NAME TEXT,
   DRIVER_NUMBER TEXT,
   SOURCE_LATITUDE DOUBLE,
   SOURCE_LONGITUDE DOUBLE,
   DEST_LATITUDE DOUBLE,
   DEST_LONGITUDE DOUBLE,
   PICKUP_ADDRESS TEXT,
   BOOKING_STATUS TEXT,
   PICKUP_TIME LONG
);